import { useEffect,useRef,useState,type FormEvent } from 'react';
import { api,ApiError,errorMessage } from '../../api/client';
import { FormError } from '../../components/States';
import type { Delivery } from './types';
import { assignmentSchema,completeSchema,driverSchema,issueSchema } from './validation';
import { AssigneePicker } from './AssigneePicker';
export type DeliveryAction='send'|'driver'|'deliver'|'issue'|'assign';
const titles:Record<DeliveryAction,string>={send:'Mark as Sent',driver:'Update driver details',deliver:'Confirm Delivered',issue:'Report delivery issue',assign:'Assign delivery user'};
export function DeliveryDialog({row,action,onClose,onSaved,onReload}:{row:Delivery;action:DeliveryAction;onClose:()=>void;onSaved:()=>void;onReload:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null),[driver,setDriver]=useState(row.driver_number??''),[name,setName]=useState(row.driver_or_bus_name??''),[bus,setBus]=useState(row.bus_number??''),[user,setUser]=useState(row.assigned_delivery_user_id??''),[reason,setReason]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[uncertain,setUncertain]=useState(false);
  useEffect(()=>{dialog.current?.showModal();},[]);
  async function submit(e:FormEvent){e.preventDefault();if(busy||conflict||uncertain)return;setError(null);const input={version:row.version},parsed=action==='assign'?assignmentSchema.safeParse({...input,assigned_delivery_user_id:user||null,reason}):action==='issue'?issueSchema.safeParse({...input,reason}):action==='deliver'?completeSchema.safeParse(input):driverSchema.safeParse({...input,driver_number:driver,driver_or_bus_name:name,bus_number:bus||null});if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join(' '));return;}setBusy(true);
    try{await api('/deliveries/'+row.delivery_id+'/'+action,{method:action==='driver'?'PATCH':'POST',body:parsed.data});onSaved();onClose();}
    catch(problem){setError(errorMessage(problem));setConflict(problem instanceof ApiError&&problem.code==='VERSION_CONFLICT');setUncertain(!(problem instanceof ApiError)||problem.status===0||problem.status>=500);setBusy(false);}}
  return <dialog ref={dialog} className="status-dialog" aria-labelledby="delivery-action-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><span className="eyebrow">ORDER #{row.order_number}</span><h2 id="delivery-action-title">{titles[action]}</h2>{action==='deliver'&&<p>Confirm the product has reached the customer. This completes the delivery and its linked order.</p>}<form noValidate onSubmit={submit}><FormError message={error}/>{(conflict||uncertain)&&<div className="alert warning">{conflict?'This delivery changed elsewhere.':'The result is uncertain.'} Reload the current delivery before another update. Unsaved values in this dialog will be discarded. <button type="button" className="button secondary" onClick={()=>{onClose();onReload();}}>Reload latest delivery</button></div>}<fieldset disabled={busy||conflict||uncertain}><legend className="sr-only">Delivery update details</legend>{(action==='send'||action==='driver')&&<div className="delivery-driver-fields"><label className="field"><span>Driver number *</span><input aria-label="Driver number" type="tel" value={driver} maxLength={40} onChange={e=>setDriver(e.target.value)}/></label><label className="field"><span>Driver or bus name *</span><input aria-label="Driver or bus name" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Bus number (optional)</span><input aria-label="Bus number" value={bus} maxLength={100} onChange={e=>setBus(e.target.value)}/></label></div>}{action==='assign'&&<><AssigneePicker value={user} onChange={setUser}/><p className="field-hint">Choose an active delivery user. Clearing an assignment is allowed only while Ready for delivery.</p></>}{(action==='assign'||action==='issue')&&<label className="field"><span>{action==='issue'?'Issue reason':'Assignment reason'} *</span><textarea aria-label={action==='issue'?'Issue reason':'Assignment reason'} maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>}</fieldset><div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy||conflict||uncertain}>{busy?'Saving…':'Save delivery update'}</button></div></form></dialog>;
}
