import { expect,test,type Page } from '@playwright/test';
test.beforeEach(async({request})=>{expect((await request.post('http://127.0.0.1:3180/__test/reset-rate-limiters')).status()).toBe(204);});
async function login(page:Page,username='ayush'){await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill('Test-only-password-123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(username==='tanaji'?/\/workspace$/:/\/dashboard$/);}
async function context(page:Page,name:string) {
  const session=await (await page.request.get('/api/v1/auth/me')).json(),headers={Origin:'http://localhost:5173','X-CSRF-Token':session.csrfToken};
  const post=async(path:string,data:unknown)=>{const response=await page.request.post('/api/v1'+path,{headers:{...headers,'Idempotency-Key':crypto.randomUUID()},data});expect(response.ok(),await response.text()).toBe(true);return (await response.json()).data;};
  const customer=(await (await page.request.get('/api/v1/customers?q=Sample%20customer%2025')).json()).data[0],design=(await (await page.request.get('/api/v1/designs?q=701')).json()).data[0];
  const supplier=await post('/suppliers',{name:'Finance artisan '+name,phone:'9876543210',city:'Pune'});
  const order=await post('/orders',{customer_id:customer.id,design_id:design.id,supplier_id:supplier.id,selling_price:'5000.00',buying_price:'3000.00',delivery_name:'Finance order '+name});
  return {post,supplier,order,customer,design};
}
async function choose(page:Page,label:string,query:string){await page.getByRole('button',{name:'Choose '+label.toLowerCase(),exact:true}).click();const group=page.getByRole('group',{name:label+' selection',exact:true});await group.getByLabel('Search '+label.toLowerCase()+' options',{exact:true}).fill(query);await group.getByRole('button',{name:'Search',exact:true}).click();await group.getByRole('button',{name:new RegExp(query)}).click();}
const value=(page:Page,label:string)=>page.locator('dl > div').filter({has:page.locator('dt').getByText(label,{exact:true})}).locator('dd');
async function add(page:Page,kind:string,id:string,amount:string,direction?:string){await page.goto('/'+kind+'/new?'+(kind==='supplier-payments'?'supplier_id':'order_id')+'='+id);await expect(page.getByLabel('Amount (₹)',{exact:true})).toBeVisible();await page.getByLabel('Amount (₹)',{exact:true}).fill(amount);if(direction)await page.getByLabel('Payment direction').selectOption(direction);}
async function save(page:Page,label:string,kind:string){await page.getByRole('button',{name:label,exact:true}).click();await expect(page).toHaveURL(new RegExp('/'+kind+'/[0-9a-f-]+$'));return page.url().split('/').at(-1)!;}
async function openVoid(page:Page){await page.getByRole('button',{name:'Void record',exact:true}).click();await page.getByRole('dialog').getByLabel('Void reason').fill('Browser correction');await page.getByRole('dialog').getByRole('button',{name:'Confirm void'}).click();}
async function voidSuccess(page:Page){await openVoid(page);await expect(page.getByRole('button',{name:'Void record',exact:true})).toHaveCount(0);await expect(value(page,'Void reason')).toHaveText('Browser correction');}
test('customer receipts/refunds, balance validation and dependent voids use real APIs',async({page})=>{
  await login(page);const f=await context(page,'customers');await add(page,'customer-payments',f.order.id,'5001');await page.getByRole('button',{name:'Add customer payment',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Net receipts');await expect(page.getByLabel('Amount (₹)',{exact:true})).toHaveValue('5001');
  await page.getByLabel('Amount (₹)',{exact:true}).fill('400');const receipt=await save(page,'Add customer payment','customer-payments');await expect(value(page,'Customer balance due')).toHaveText('₹4,600.00');
  await add(page,'customer-payments',f.order.id,'500','REFUND');await page.getByRole('button',{name:'Add customer payment',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Net receipts');await page.getByLabel('Amount (₹)',{exact:true}).fill('100');const refund=await save(page,'Add customer payment','customer-payments');await expect(value(page,'Customer balance due')).toHaveText('₹4,700.00');
  await page.goto('/customer-payments/'+receipt);await openVoid(page);await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Net receipts');await page.getByRole('dialog').getByRole('button',{name:'Keep record'}).click();
  await page.goto('/customer-payments/'+refund);await voidSuccess(page);await page.goto('/customer-payments/'+receipt);await voidSuccess(page);await expect(value(page,'Customer balance due')).toHaveText('₹5,000.00');
  await page.goto('/customer-payments?order_id='+f.order.id+'&status=VOID');await expect(page.getByText('2 records',{exact:true})).toBeVisible();
});
test('supplier payments allocate now and later; refunds and voids preserve balance rules',async({page})=>{
  await login(page);const f=await context(page,'suppliers'),second=await f.post('/orders',{customer_id:f.customer.id,design_id:f.design.id,supplier_id:f.supplier.id,selling_price:'4000',buying_price:'2000',delivery_name:'Finance second allocation'});
  await add(page,'supplier-payments',f.supplier.id,'5001');await page.getByRole('button',{name:'Add supplier payment',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Payment exceeds');await page.getByLabel('Amount (₹)',{exact:true}).fill('1500');await page.getByRole('button',{name:'Add allocation',exact:true}).click();await choose(page,'Allocation order 1',f.order.order_number);await page.getByLabel('Allocation amount 1 (₹)',{exact:true}).fill('1000');const payment=await save(page,'Add supplier payment','supplier-payments');await expect(value(page,'Supplier pending amount')).toHaveText('₹3,500.00');
  await page.getByRole('link',{name:'Allocate to orders',exact:true}).click();await page.getByRole('button',{name:'Add allocation',exact:true}).click();await choose(page,'Allocation order 1',second.order_number);await page.getByLabel('Allocation amount 1 (₹)',{exact:true}).fill('501');await page.getByRole('button',{name:'Save allocations'}).click();await expect(page.getByRole('alert')).toContainText('exceed the unallocated');await page.getByLabel('Allocation amount 1 (₹)',{exact:true}).fill('500');await page.getByRole('button',{name:'Save allocations'}).click();await expect(page.getByText('Order allocations saved.')).toBeVisible();await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(2);
  await add(page,'supplier-payments',f.supplier.id,'200','REFUND');await page.getByRole('button',{name:'Add supplier payment',exact:true}).click();await expect(page.getByRole('alert')).toContainText('refund/void');await page.getByRole('button',{name:'Add allocation',exact:true}).click();await choose(page,'Allocation order 1',f.order.order_number);await page.getByLabel('Allocation amount 1 (₹)',{exact:true}).fill('200');const refund=await save(page,'Add supplier payment','supplier-payments');await expect(value(page,'Supplier pending amount')).toHaveText('₹3,700.00');
  await page.goto('/supplier-payments/'+payment);await openVoid(page);await expect(page.getByRole('dialog').getByRole('alert')).toContainText('refund/void');await page.getByRole('dialog').getByRole('button',{name:'Keep record'}).click();await page.goto('/supplier-payments/'+refund);await voidSuccess(page);await page.goto('/supplier-payments/'+payment);await voidSuccess(page);await expect(value(page,'Supplier pending amount')).toHaveText('₹5,000.00');await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(2);
});
test('expenses change backend profit and void restores it without changing customer balance',async({page})=>{
  await login(page);const f=await context(page,'expenses');await add(page,'order-expenses',f.order.id,'300');const delivery=await save(page,'Add order expense','order-expenses');await add(page,'order-expenses',f.order.id,'100');await page.getByLabel('Expense category').selectOption('OTHER');await save(page,'Add order expense','order-expenses');await page.getByRole('link',{name:'View order financial summary',exact:true}).click();await expect(value(page,'Profit')).toHaveText('₹1,600.00');await expect(value(page,'Customer balance due')).toHaveText('₹5,000.00');await expect(value(page,'Delivery expense')).toHaveText('₹300.00');
  if(process.env.PHASE10_SCREENSHOT_DIR)await page.screenshot({path:process.env.PHASE10_SCREENSHOT_DIR+'/order-financials-desktop.png',fullPage:true});
  await page.goto('/order-expenses/'+delivery);await voidSuccess(page);await page.getByRole('link',{name:'View order financial summary',exact:true}).click();await expect(value(page,'Profit')).toHaveText('₹1,900.00');await page.getByRole('link',{name:'Order expenses',exact:true}).last().click();await expect(page.getByText('1 record',{exact:true})).toBeVisible();
});
test('a lost money response is explicitly retried with the same key and creates one receipt',async({page})=>{
  await login(page);const f=await context(page,'retry'),seen:{key:string|undefined;body:string|null}[]=[];let lose=true;
  await page.route('**/api/v1/customer-payments',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}seen.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});if(lose){lose=false;const response=await route.fetch();expect(response.status()).toBe(201);await route.abort('failed');}else await route.continue();});
  await add(page,'customer-payments',f.order.id,'123.45');await page.getByRole('button',{name:'Add customer payment',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same submission'})).toBeVisible();await expect(page.getByLabel('Amount (₹)',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same submission'}).click();await expect(page).toHaveURL(/\/customer-payments\/[0-9a-f-]+$/);expect(seen).toHaveLength(2);expect(seen[0]).toEqual(seen[1]);
  const list=await (await page.request.get('/api/v1/customer-payments?order_id='+f.order.id)).json();expect(list.meta.total).toBe(1);await expect(value(page,'Customer balance due')).toHaveText('₹4,876.55');
});
test('financial lists paginate/filter, recover read failures and show backend field errors',async({page})=>{
  await login(page);const f=await context(page,'lists');await page.goto('/customer-payments?order_id='+f.order.id);await expect(page.getByRole('heading',{name:'No matching financial records'})).toBeVisible();
  for(let i=0;i<11;i++)await f.post('/customer-payments',{order_id:f.order.id,direction:'RECEIPT',purpose:'OTHER',amount:'1',payment_date:'2026-10-02',payment_method:'CASH'});
  await page.reload();await page.getByLabel('Records per page').selectOption('10');await page.getByRole('button',{name:'Apply filters'}).click();await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(10);await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText(/Page 2 of 2/)).toBeVisible();await page.getByLabel('Direction filter').selectOption('REFUND');await page.getByRole('button',{name:'Apply filters'}).click();await expect(page.getByRole('heading',{name:'No matching financial records'})).toBeVisible();
  await page.route('**/api/v1/order-expenses?*',route=>route.fulfill({status:503,json:{error:{code:'TEMPORARY',message:'Test read unavailable'}}}));await page.goto('/order-expenses?order_id='+f.order.id);await expect(page.getByRole('alert')).toContainText('Test read unavailable');await page.unroute('**/api/v1/order-expenses?*');await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByRole('heading',{name:'No matching financial records'})).toBeVisible();
  await page.goto('/customer-payments?status=bad');await expect(page.getByRole('alert')).toContainText('Invalid financial filters');
  await page.route('**/api/v1/order-expenses',route=>route.request().method()==='POST'?route.fulfill({status:400,json:{error:{code:'VALIDATION_ERROR',message:'Check the submitted fields.',fields:['amount','expense_date']}}}):route.continue());await add(page,'order-expenses',f.order.id,'10');await page.getByRole('button',{name:'Add order expense',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Fields: amount, expense date.');await expect(page.getByLabel('Amount (₹)',{exact:true})).toHaveValue('10');
});
test('DELIVERY financial routes/APIs deny access; mobile forms, allocations and lists fit',async({page})=>{
  await login(page,'tanaji');for(const path of ['/customer-payments','/supplier-payments/new','/order-expenses/new','/supplier-payments/12345678-1234-4123-8123-123456789012/allocations']){await page.goto(path);await expect(page).toHaveURL(/\/workspace$/);}for(const path of ['customer-payments','supplier-payments','order-expenses'])expect((await page.request.get('/api/v1/'+path)).status()).toBe(403);await page.getByRole('button',{name:'Sign out',exact:true}).click();await login(page);const f=await context(page,'mobile');await page.setViewportSize({width:390,height:844});await add(page,'supplier-payments',f.supplier.id,'500');await page.getByRole('button',{name:'Add allocation',exact:true}).click();await choose(page,'Allocation order 1',f.order.order_number);await page.getByLabel('Allocation amount 1 (₹)',{exact:true}).fill('300');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  if(process.env.PHASE10_SCREENSHOT_DIR){await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:process.env.PHASE10_SCREENSHOT_DIR+'/supplier-payment-mobile.png',fullPage:true});}await save(page,'Add supplier payment','supplier-payments');await page.goto('/supplier-payments?supplier_id='+f.supplier.id);await expect(page.getByRole('table')).toBeVisible();for(const width of [320,390,768]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:390,height:844});if(process.env.PHASE10_SCREENSHOT_DIR){await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:process.env.PHASE10_SCREENSHOT_DIR+'/supplier-list-mobile.png',fullPage:true});}
});
