import { useEffect,useRef,useState } from 'react';
import { NavLink,Outlet,useLocation } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { errorMessage } from '../api/client';
import { Icon } from './Icon';
import { FormError } from './States';
export function Layout() {
  const {session,logout}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),drawer=useRef<HTMLDialogElement>(null),main=useRef<HTMLElement>(null);
  const location=useLocation(),admin=session!.user.role==='ADMIN';
  useEffect(()=>{drawer.current?.close();main.current?.focus();setError(null);
    const section=location.pathname.split('/')[1];document.title=(section?section.charAt(0).toUpperCase()+section.slice(1):'Workspace')+' · DivyaShilla';
  },[location.pathname]);
  const navigation=admin?[{to:'/dashboard',label:'Dashboard',icon:'dashboard' as const},{to:'/deliveries',label:'Deliveries',icon:'suppliers' as const},{to:'/orders',label:'Orders',icon:'designs' as const},{to:'/customers',label:'Customers',icon:'customers' as const},
    {to:'/designs',label:'Designs',icon:'designs' as const},{to:'/suppliers',label:'Suppliers',icon:'suppliers' as const},{to:'/customer-payments',label:'Customer payments',icon:'customers' as const},{to:'/supplier-payments',label:'Supplier payments',icon:'suppliers' as const},{to:'/order-expenses',label:'Order expenses',icon:'dashboard' as const}]:[{to:'/workspace',label:'Dashboard',icon:'dashboard' as const},{to:'/deliveries',label:'My deliveries',icon:'suppliers' as const}];
  const links=<><div className="sidebar-brand"><span className="brand-mark"><Icon name="designs" size={26}/></span><span>DivyaShilla<small>BUSINESS WORKSPACE</small></span></div><div className="nav-label">YOUR WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(item=><NavLink key={item.to} to={item.to} onClick={()=>drawer.current?.close()}><Icon name={item.icon}/><span>{item.label}</span></NavLink>)}</nav><div className="sidebar-bottom"><span className="small-dot"/> Internal business management<small>Stone craft. Strong foundations.</small></div></>;
  return <div className="app-shell"><a href="#main" className="skip-link">Skip to content</a><aside className="sidebar">{links}</aside><dialog ref={drawer} id="mobile-navigation" className="nav-dialog" aria-label="Navigation"><button className="icon-button drawer-close" aria-label="Close navigation" onClick={()=>drawer.current?.close()}><Icon name="close"/></button>{links}</dialog><div className="workspace"><header className="topbar"><div className="topbar-left"><button className="icon-button menu-button" aria-label="Open navigation" aria-controls="mobile-navigation" onClick={()=>drawer.current?.showModal()}><Icon name="menu"/></button><span className="topbar-label">Business workspace</span><span className="topbar-divider"/><span className="role-label">{admin?'Administrator':'Delivery team'}</span></div><div className="topbar-right"><span className="avatar">{session!.user.name.slice(0,1).toUpperCase()}</span><span className="user-name">{session!.user.name}</span><button className="icon-button" aria-label="Sign out" title="Sign out" disabled={busy} onClick={()=>{if(busy)return;setBusy(true);void logout().catch(e=>setError(errorMessage(e))).finally(()=>setBusy(false));}}><Icon name="logout"/></button></div></header><main id="main" ref={main} tabIndex={-1} className="main-content"><FormError message={error}/><Outlet/></main><footer className="workspace-footer">DivyaShilla <span>Built for the everyday details.</span></footer></div></div>;
}
