import { useResource } from '../../api/useResource';
import type { OrderDetail } from '../orders/types';
import { rupees } from '../dashboard/format';
import { OrderPicker } from './OrderPicker';
import type { Allocation } from './types';
import { cents,decimal,positiveMoney } from './validation';
export function allocationTotal(rows:Allocation[]) {return rows.reduce((n,row)=>{const v=positiveMoney.safeParse(row.amount);return n+(v.success?cents(v.data):0n);},0n);}
function OrderAllocationSummary({id}:{id:string}) {
  const resource=useResource<{data:OrderDetail}>('/orders/'+id),row=resource.data?.data;
  return resource.loading?<p className="field-hint" role="status">Loading allocation balance…</p>:resource.error?<p className="field-hint">Could not load order balance. <button type="button" className="button text compact" onClick={resource.reload}>Retry allocation balance</button></p>:row?<p className="field-hint">Buying cost {row.buying_price===null?'unknown':rupees(row.buying_price)} · Allocations are checked against the current posted history when saved.</p>:null;
}
export function AllocationRows({rows,onChange,supplierId,excluded=[],remaining,disabled=false}:{rows:Allocation[];onChange:(rows:Allocation[])=>void;supplierId:string;excluded?:string[];remaining?:string;disabled?:boolean}) {
  return <section className="panel"><div className="section-heading"><h2>Order allocations</h2><span>{rows.length} / 100</span></div><p className="field-hint">Allocate positive amounts to this supplier's priced orders. For refunds, allocations reduce the amounts previously paid to those orders. Unallocated money can be assigned later.</p>{remaining&&<p className="allocation-total">Available on this record: <strong>{rupees(remaining)}</strong> · Selected total: <strong>{rupees(decimal(allocationTotal(rows)))}</strong></p>}{!rows.length&&<p className="muted">No allocations added.</p>}{rows.map((row,index)=><div className="allocation-row" key={index}><div className="allocation-fields"><OrderPicker label={'Allocation order '+(index+1)} value={row.order_id} supplierId={supplierId} required excluded={[...excluded,...rows.filter((_,i)=>i!==index).map(r=>r.order_id)]} disabled={disabled} onChange={id=>onChange(rows.map((r,i)=>i===index?{...r,order_id:id}:r))}/><label className="field"><span>Allocation amount {index+1} (₹) *</span><input aria-label={'Allocation amount '+(index+1)+' (₹)'} inputMode="decimal" maxLength={15} value={row.amount} disabled={disabled} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,amount:e.target.value}:r))}/></label><button type="button" className="button text" aria-label={'Remove allocation '+(index+1)} disabled={disabled} onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>Remove</button></div>{row.order_id&&<OrderAllocationSummary id={row.order_id}/>}</div>)}<button type="button" className="button secondary" disabled={disabled||!supplierId||rows.length>=100} onClick={()=>onChange([...rows,{order_id:'',amount:''}])}>Add allocation</button>{!supplierId&&<p className="field-hint">Choose a supplier first.</p>}</section>;
}
