import { useResource } from '../../api/useResource';
import { ErrorState,Loading } from '../../components/States';
import { rupees } from '../dashboard/format';
import type { CustomerBalance,SupplierBalance } from './types';
export function CustomerBalancePanel({orderId}:{orderId:string}) {
  const resource=useResource<{data:CustomerBalance}>('/customer-payments/orders/'+orderId+'/balance'),row=resource.data?.data;
  return <section className="panel balance-panel"><div className="section-heading"><h2>Customer balance{row?' · Order #'+row.order_number:''}</h2><button type="button" className="button text compact" onClick={resource.reload}>Refresh balance</button></div>{resource.loading?<Loading label="Loading customer balance…"/>:resource.error?<ErrorState message={resource.error} retry={resource.reload}/>:row?<><dl className="financial-grid">{[{label:'Selling price',value:row.selling_price},{label:'Net customer receipts',value:row.customer_net_received},{label:'Customer balance due',value:row.balance_amount},{label:'Recorded advance receipts',value:row.advance_receipts_recorded}].map(item=><div key={item.label}><dt>{item.label}</dt><dd>{rupees(item.value)}</dd></div>)}</dl><p className="field-hint">Current posted receipts less refunds. Agreed advance {rupees(row.advance_amount)} is a target; recorded advance receipts count posted Advance receipts before refunds.</p></>:null}</section>;
}
export function SupplierBalancePanel({supplierId}:{supplierId:string}) {
  const resource=useResource<{data:SupplierBalance}>('/supplier-payments/suppliers/'+supplierId+'/balance'),row=resource.data?.data;
  return <section className="panel balance-panel"><div className="section-heading"><h2>Supplier balance{row?' · '+row.name:''}</h2><button type="button" className="button text compact" onClick={resource.reload}>Refresh balance</button></div>{resource.loading?<Loading label="Loading supplier balance…"/>:resource.error?<ErrorState message={resource.error} retry={resource.reload}/>:row?<><dl className="financial-grid">{[{label:'Known buying cost',value:row.known_liability},{label:'Net supplier payments',value:row.net_paid},{label:'Supplier pending amount',value:row.payable},{label:'Unallocated net payments',value:row.unallocated_net_advance}].map(item=><div key={item.label}><dt>{item.label}</dt><dd>{rupees(item.value)}</dd></div>)}</dl>{Number(row.unpriced_orders)>0&&<div className="alert warning">{row.unpriced_orders} orders have unknown buying prices. Their costs are not included in the pending amount.</div>}<p className="field-hint">Current posted payments less refunds. Cancelled orders retain their buying costs. Allocation assigns an existing payment to an order; it does not pay money again.</p></>:null}</section>;
}
