import { useState } from 'react';
import { useResource } from '../../api/useResource';
import { FormError } from '../../components/States';
import { rupees } from '../dashboard/format';
import type { Order,OrderDetail,OrdersPage } from '../orders/types';
interface Props {label?:string;value:string;onChange:(id:string)=>void;disabled?:boolean;error?:string;supplierId?:string;excluded?:string[];required?:boolean}
export function OrderPicker({label='Order',value,onChange,disabled,error,supplierId,excluded=[],required=false}:Props) {
  const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1);
  const selected=useResource<{data:OrderDetail}>(value?'/orders/'+value:null);
  const params=new URLSearchParams({q:query,page:String(page),limit:'10',sort_by:'order_number',sort_order:'desc',...(supplierId?{supplier_id:supplierId}:{})});
  const options=useResource<OrdersPage>(open&&!disabled?'/orders?'+params:null);
  const unavailable=(row:Order)=>excluded.includes(row.id)||(Boolean(supplierId)&&(row.supplier_id!==supplierId||row.buying_price===null));
  return <div className="field record-picker"><label>{label}{required&&<span className="required">*</span>}</label><div className="picker-selected"><button type="button" className="picker-trigger" aria-label={'Choose '+label.toLowerCase()} aria-expanded={open&&!disabled} disabled={disabled} onClick={()=>setOpen(v=>!v)}>{selected.data?'#'+selected.data.data.order_number+' · '+selected.data.data.delivery_name:value?'Loading order…':'Choose order'}<span aria-hidden="true">⌄</span></button>{value&&!disabled&&!required&&<button className="button text compact" type="button" aria-label={'Clear '+label.toLowerCase()} onClick={()=>onChange('')}>Clear</button>}</div>{selected.error&&<div className="picker-warning">Order details unavailable. <button className="button text compact" type="button" onClick={selected.reload}>Retry order</button></div>}{error&&<small role="alert" className="field-error">{error}</small>}{open&&!disabled&&<div className="picker-panel" role="group" aria-label={label+' selection'}><div className="picker-search"><input aria-label={'Search '+label.toLowerCase()+' options'} value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} placeholder="Order number, recipient or design"/><button type="button" className="button secondary compact" onClick={()=>{setQuery(search.trim());setPage(1);}}>Search</button><button type="button" className="button text compact" onClick={()=>setOpen(false)}>Close</button></div>{options.loading?<p role="status">Loading orders…</p>:options.error?<><FormError message={options.error}/><button className="button secondary compact" type="button" onClick={options.reload}>Retry options</button></>:!options.data?.data.length?<p>No matching orders.</p>:<ul>{options.data.data.map(row=><li key={row.id}><button type="button" disabled={unavailable(row)} onClick={()=>{onChange(row.id);setOpen(false);}}><strong>#{row.order_number} · {row.delivery_name}</strong><small>{row.design_number_snapshot} · {row.delivery_city}{supplierId?' · Buying '+(row.buying_price===null?'unknown':rupees(row.buying_price)):''}{excluded.includes(row.id)?' · Already allocated':''}</small></button></li>)}</ul>}{supplierId&&<p>Only this supplier's orders with a known buying price can be allocated.</p>}{options.data&&options.data.meta.total_pages>1&&<div className="picker-pagination"><button type="button" className="button secondary compact" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous options</button><span>{page} / {options.data.meta.total_pages}</span><button type="button" className="button secondary compact" disabled={page>=options.data.meta.total_pages} onClick={()=>setPage(p=>p+1)}>Next options</button></div>}</div>}</div>;
}
