import { useEffect,useState } from 'react';
import type { MasterRecord,PageResult } from '../../api/types';
import { useResource } from '../../api/useResource';
import { masterConfigs,text,type MasterKind } from '../masters/config';
import { FormError } from '../../components/States';
interface Props {kind:MasterKind;label:string;value:string;onChange:(id:string,record?:MasterRecord)=>void;disabled?:boolean;error?:string;fallback?:string;includeInactive?:boolean;required?:boolean}
export function RecordPicker({kind,label,value,onChange,disabled,error,fallback,includeInactive=false,required=false}:Props) {
  const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1);
  const selected=useResource<{data:MasterRecord}>(value?'/'+kind+'/'+value:null);
  const results=useResource<PageResult>(open&&!disabled?'/'+kind+'?'+new URLSearchParams({q:query,status:includeInactive?'all':'active',page:String(page),limit:'10',sort_by:kind==='designs'?'design_number':'name',sort_order:'asc'}):null);
  useEffect(()=>{if(disabled)setOpen(false);},[disabled]);
  const config=masterConfigs[kind],display=(row:MasterRecord)=>kind==='designs'?text(row.design_number)+' · '+text(row.design_name):text(row[config.nameKey]);
  return <div className="field record-picker"><label>{label}{required&&<span className="required">*</span>}</label><div className="picker-selected"><button type="button" className="picker-trigger" disabled={disabled} aria-label={'Choose '+label.toLowerCase()} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{value?(selected.data?display(selected.data.data):(fallback||'Loading selection…')):'Choose '+config.singular}<span aria-hidden="true">⌄</span></button>{value&&!disabled&&!required&&<button className="button text compact" type="button" aria-label={'Clear '+label.toLowerCase()} onClick={()=>onChange('')}>Clear</button>}</div>{selected.error&&value&&<div className="picker-warning" role="status">{fallback||'Saved selection'} · Current record unavailable. <button className="button text compact" type="button" onClick={selected.reload}>Retry</button></div>}{selected.data&&!selected.data.data.is_active&&<small className="field-hint">Inactive record. Its existing order link can be retained.</small>}{error&&<small className="field-error" role="alert">{error}</small>}{open&&!disabled&&<div className="picker-panel" role="group" aria-label={label+' selection'}><div className="picker-search"><input aria-label={'Search '+label.toLowerCase()+' options'} value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder={'Search '+config.title.toLowerCase()}/><button type="button" className="button secondary compact" onClick={()=>{setQuery(search.trim());setPage(1);}}>Search</button><button type="button" className="button text compact" aria-label={'Close '+label.toLowerCase()+' options'} onClick={()=>setOpen(false)}>Close</button></div>{results.loading?<p role="status">Loading options…</p>:results.error?<><FormError message={results.error}/><button type="button" className="button secondary compact" onClick={results.reload}>Retry options</button></>:results.data?.data.length===0?<p>No matching {config.title.toLowerCase()}. Try another search.</p>:<ul>{results.data?.data.map(row=><li key={row.id}><button type="button" onClick={()=>{onChange(row.id,row);setOpen(false);}}><strong>{display(row)}</strong><small>{kind==='designs'?text(row.size)+' · '+text(row.material):text(row.phone)+(text(row.city)?' · '+text(row.city):'')}{!row.is_active?' · Inactive':''}</small></button></li>)}</ul>}{results.data&&results.data.meta.total_pages>1&&<div className="picker-pagination"><button type="button" disabled={page<=1} className="button secondary compact" onClick={()=>setPage(v=>v-1)}>Previous options</button><span>{page} / {results.data.meta.total_pages}</span><button type="button" disabled={page>=results.data.meta.total_pages} className="button secondary compact" onClick={()=>setPage(v=>v+1)}>Next options</button></div>}</div>}</div>;
}
